# -*- coding: utf-8 -*-
"""3_Challenge_AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_BwPg9TsoRRcd8mMpGXDVTt_toZ1Ynr

### Importación de datos
"""

import pandas as pd

url1 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda1 = pd.read_csv(url1)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda1.head()

"""#1. Análisis de facturación 📈

### 1.1 Facturación por tienda 🏬 🏪 💰 💸
"""

#Algunos ajustes previos para la visualización de los datos
pd.set_option('expand_frame_repr', False)
pd.set_option('display.max_columns', None)

lista_tiendas = [tienda1, tienda2, tienda3, tienda4]  # Crea una lista con los DataFrames de las tiendas
print("********** FACTURACION TOTAL POR TIENDA ********** \n")

#Función que calcula la facturación para cada una de las tiendas:
def imprimir_facturacion(tiendas):
  """Recibe una lista de DataFrames y calcula la facturación
  a partir de la columna Precio """
  contador = 1
  lista_aux = []
  for facturacion in tiendas:
    monto = sum(facturacion["Precio"])
    lista_aux.append(monto)
    print(f"Facturación total de la Tienda {contador}: {monto:,.2f}", "\n")
    contador += 1
  return lista_aux

facturación_por_tienda = imprimir_facturacion(lista_tiendas)

"""###1.2 Gráfico de facturación por tiendas 📊 💲 💵"""

import matplotlib.pyplot as plt
import numpy as np

tiendas = ["Tienda 1", "Tienda 2", "Tienda 3", "Tienda 4"]
facturacion = facturación_por_tienda

#Colores de Barras
bar_labels = ['red', 'blue', '_red', 'orange']
bar_colors = ['tab:green', 'tab:blue', 'tab:red', 'tab:orange']

#Montos en Barras
fig, ax = plt.subplots()
bar_container = ax.bar(tiendas, facturacion)
#ax.set(ylabel='pints sold', title='', ylim=(0, 8000))
ax.bar_label(bar_container, fmt='{:,.0f}')

#Dibuja un gráfico de barras
plt.bar(tiendas, facturacion, label=bar_labels, color=bar_colors)
plt.title("Facturación por tienda - Ene 2020 / Dic 2023")
plt.xlabel("Tiendas")
plt.ylabel("Montos")
plt.gcf().axes[0].yaxis.get_major_formatter().set_scientific(False)
plt.show()

"""# 2. Ventas por categoría

###2.1 Totales de ventas por categoria de cada tienda 💲📃 🏢
"""

nombre_tiendas = {"tiendas": ["TIENDA 1", "TIENDA 2", "TIENDA 3", "TIENDA 4"]}

lista_categorias = []   #almacena las categorías para comparación
# Crea una lista con las categorías
for categoria in tienda["Categoría del Producto"]:
  if categoria not in lista_categorias:
    lista_categorias.append(categoria)

# Función que suma los montos de la facturación por categoría
def monto_categoria(tienda):
  """Esta función recibe como parámetro un DataFrame de una tienda
  y calcula los montos de facturación por categoría de producto"""
  monto_categoria_tienda = []
  monto_total = 0
  for categoria in lista_categorias:
    for i, monto in enumerate(tienda['Precio']):
      if categoria == tienda['Categoría del Producto'][i]:
        monto_total += monto
    monto_categoria_tienda.append(monto_total)
    monto_total = 0
  return monto_categoria_tienda

#listas con los montos por categoría por tienda
monto_categoria_tienda_1 = monto_categoria(tienda1)
monto_categoria_tienda_2 = monto_categoria(tienda2)
monto_categoria_tienda_3 = monto_categoria(tienda3)
monto_categoria_tienda_4 = monto_categoria(tienda4)


#lista de listas con los montos por categoria
listas_monto_categoria = [monto_categoria_tienda_1, monto_categoria_tienda_2, monto_categoria_tienda_3, monto_categoria_tienda_4]

#Crea un diccionario con la facturación (montos) por categoría para cada tienda (tabla)
lista_aux = []
tabla_montos_categoria = {}
for i, categoria in enumerate(lista_categorias):
  for montos in listas_monto_categoria:
    lista_aux.append(montos[i])
  tabla_montos_categoria[categoria] = lista_aux
  lista_aux = []

#Imprime la tabla en pantalla
print("------ TABLA: FACTURACION POR CATEGORIA -----\n")
tabla_montos_categoria = {**nombre_tiendas, **tabla_montos_categoria}
pd.DataFrame(tabla_montos_categoria)

"""###2.2 Cantidad de productos vendidos por categoria 📃 🔖"""

#Función que suma la cantidad de productos vendidos por categoría
def cantidad_productos(tienda):
  """Recibe como parámetro un DataFrame de una tienda y calcula la
  cantidad de productos vendidor por categoría"""
  contador = 0
  cantidad_productos_tienda = []
  for categoria in lista_categorias:
    for i, categoria_producto in enumerate(tienda['Categoría del Producto']):
      if categoria == categoria_producto:
        contador += 1
    cantidad_productos_tienda.append(contador)
    contador = 0
  return cantidad_productos_tienda

# Listas que contienen la cantidad de ventas por categoría de producto por tienda
cantidad_productos_tienda_1 = cantidad_productos(tienda1)
cantidad_productos_tienda_2 = cantidad_productos(tienda2)
cantidad_productos_tienda_3 = cantidad_productos(tienda3)
cantidad_productos_tienda_4 = cantidad_productos(tienda4)

#lista de listas con los productos vendidos por categoria por tienda
productos_por_tienda = [cantidad_productos_tienda_1, cantidad_productos_tienda_2, cantidad_productos_tienda_3, cantidad_productos_tienda_4]

#crea un diccionario de la cantidad de productos por categoría por tienda (tabla)
total_por_producto = [] #lista con la sumatoria de productos por categoría vendidos por todas las tiendas
lista_aux = []
tabla_cantidad_productos = {}   #lista de listas
for i, categoria in enumerate(lista_categorias):
  for cantidad_productos in productos_por_tienda:
    lista_aux.append(cantidad_productos[i])
  total_por_producto.append(sum(lista_aux))   #calcula total por producto y lo guarda
  tabla_cantidad_productos[categoria] = lista_aux   #guarda lista en la lista tabla_cantidad_productos
  lista_aux = []

#Imprime la tabla
print("------ TABLA: PRODUCTOS VENDIDOS POR CATEGORIA -----\n")
tabla_cantidad_productos = {**nombre_tiendas, **tabla_cantidad_productos}
pd.DataFrame(tabla_cantidad_productos)

"""###2.3. Grafico de resultados, ventas por categoría: 📊 💲 📑"""

#Gráfico barras horizontales por totales por categoría de productos

plt.barh(lista_categorias, total_por_producto, color = "navy")
plt.title("Ventas por categoría (todas las tiendas)")
plt.xlabel("Cantidad de productos")
plt.show()

#Gráfico de barras por totales por categoría de productos

#Montos en Barras
fig, ax = plt.subplots()
bar_container = ax.bar(lista_categorias, total_por_producto)
#ax.set(ylabel='pints sold', title='', ylim=(0, 8000))
ax.bar_label(bar_container, fmt='{:,.0f}')

color_barra = ['green', 'red', 'orange', 'blue', 'navy', 'purple', 'pink', 'yellow']
plt.bar(lista_categorias, total_por_producto, color = color_barra)
plt.title("Ventas por categoría (todas las tiendas)")
plt.ylabel("Cantidad de productos")
plt.xticks(rotation = 90)
plt.show()

print("En color rojo las categorías más vendidas")

# Crea un Pie chart para las ventas de productos por categoría para todas las tiendas
plt.pie(total_por_producto, labels = lista_categorias)
plt.title("Ventas por categoría")
plt.show()

nombre_tiendas = tabla_cantidad_productos["tiendas"]  #crea una lista con los nombres de las tiendas

# Crea un diccionario de la cantidad vendida de productos por categoría por tienda sin la clave "tiendas"
categorias_ventas = {clave: valores for (clave, valores) in tabla_cantidad_productos.items() if clave != "tiendas"}

x = np.arange(len(nombre_tiendas))   #ubicacion de las etiquetas
ancho_barra = 0.10  #ancho de las barras
multiplicador = 0

fig, ax = plt.subplots(figsize =(17, 7))

for categoria, cantidad in categorias_ventas.items():
  offset = ancho_barra * multiplicador
  contenedor = ax.bar(x + offset, cantidad, ancho_barra, label = categoria)
  ax.bar_label(contenedor, padding = 3)
  multiplicador += 1

# COnfiguración de la gráfica (texto, etiquetas, ticks del eje etc.)
ax.set_ylabel("Cantidad productos")
ax.set_title("Ventas según categoría por tienda")
ax.set_xticks(x + ancho_barra * 3.5, nombre_tiendas)
ax.legend(loc='upper left', ncols = 3)
ax.set_ylim(0, 600)
plt.show()

"""# 3. Calificación promedio de la tienda

"""

# Función que crea una lista con las calificaciones de las tiendas
def calcular_calificacion(lista):
  lista_aux = []
  for elemento in lista:
    promedio = sum(elemento["Calificación"]) / len(elemento["Calificación"])
    lista_aux.append(promedio)
  return lista_aux

# Muestra la lista generada de las calificaciones promedio
calificacion_promedio_tiendas = calcular_calificacion(lista_tiendas)
print("======== CALIFICACION PROMEDIO POR TIENDA ========")
pd.Series(calificacion_promedio_tiendas, index = tiendas)

"""###3.1. Grafico de datos de las calificaciones de las ventas 📈 💲📄"""

#Preparación de los datos para armar una tabla y las gráficas
lista_auxiliar = []
calificacion_por_tiendas = []  #Lista de lista con los datos de las calificaciones para cada tienda
for x in range(1, 6):
  for tienda_aux in lista_tiendas:
    lista_auxiliar.append(list(tienda_aux['Calificación']).count(x))
  calificacion_por_tiendas.append(lista_auxiliar)
  lista_auxiliar = []

import matplotlib.ticker as ticker
# lista con etiquetas para la gráfica
etiquetas_puntaje = ["1 punto", "2 puntos", "3 puntos", "4 puntos", "5 puntos"]

# crea un diccionario con datos para la gráfica
datos_puntaje = {llaves : valores for (llaves, valores) in zip(etiquetas_puntaje, calificacion_por_tiendas)}

ancho_barras = 0.6  # ancho de las barras

fig, ax = plt.subplots(figsize = (7, 8))
bottom = np.zeros(4)

#crea las barras de la gráfica
for etiquetas, puntajes in datos_puntaje.items():
  contenedor = ax.bar(tiendas, puntajes, ancho_barras, label = etiquetas, bottom = bottom)
  bottom += puntajes
  ax.bar_label(contenedor, label_type = "center")

ax.set_title("Calificaciones dadas a las ventas")
ax.legend()
ax.set_ylim(0, 3000)
ax.yaxis.set_major_locator(ticker.NullLocator())
plt.show()

"""# 4. Productos más y menos vendidos"""

# crear una lista con los valores únicos de la lista de productos
nombre_productos = tienda['Producto'].unique()
nombre_productos.sort()
dic_temp = {}
dic_temp["Producto"] = nombre_productos

# crear una lista de las cantidades de productos vendidos por tipo en cada tienda
cantidad_productos_vendidos = []
lista_auxiliar = []

for una_tienda in lista_tiendas:
  for producto_n in nombre_productos:
    lista_auxiliar.append(list(una_tienda["Producto"]).count(producto_n))
  cantidad_productos_vendidos.append(lista_auxiliar)
  lista_auxiliar = []

#crear un diccionario con 4 listas, una por tienda, con la cantidad de productos por tipo
tabla_cantidad_productos = {llaves:valores for (llaves, valores) in zip(tiendas, cantidad_productos_vendidos)}

#agregar la columna de nombres de los productos al diccionario
tabla_cantidad_productos = {**dic_temp, **tabla_cantidad_productos}

#crear un DataFrame a partir del diccionario de productos
tabla_productos = pd.DataFrame(tabla_cantidad_productos)

#muestrar la tabla con las cantidades de TODOS los productos vendidos por tienda
tabla_productos

"""###4.1. Grafico de productos más o menos vendidos por tienda 📊 🏪"""

#crear una tabla de los productos ordenada por la columna Tienda 1
tabla_productos_ordenada_tienda_1 = tabla_productos.sort_values(by = "Tienda 1")

#crear dos tablas: los 10 productos más vendidos y 10 menos vendidos, tienda 1
productos_mas_vendidos_t1 = tabla_productos_ordenada_tienda_1.tail(10)
productos_menos_vendidos_t1 = tabla_productos_ordenada_tienda_1.head(10)

#crear una tabla de los productos ordenada por la columna Tienda 2
tabla_productos_ordenada_tienda_2 = tabla_productos.sort_values(by = "Tienda 2")

#crear dos tablas: los 10 productos más vendidos y 10 menos vendidos, tienda 2
productos_mas_vendidos_t2 = tabla_productos_ordenada_tienda_2.tail(10)
productos_menos_vendidos_t2 = tabla_productos_ordenada_tienda_2.head(10)

#crear una tabla de los productos ordenada por la columna Tienda 3
tabla_productos_ordenada_tienda_3 = tabla_productos.sort_values(by = "Tienda 3")

#crear dos tablas: los 10 productos más vendidos y 10 menos vendidos, tienda 3
productos_mas_vendidos_t3 = tabla_productos_ordenada_tienda_3.tail(10)
productos_menos_vendidos_t3 = tabla_productos_ordenada_tienda_3.head(10)

#crear una tabla de los productos ordenada por la columna Tienda 4
tabla_productos_ordenada_tienda_4 = tabla_productos.sort_values(by = "Tienda 4")

#crear dos tablas: los 10 productos más vendidos y 10 menos vendidos, tienda 4
productos_mas_vendidos_t4 = tabla_productos_ordenada_tienda_4.tail(10)
productos_menos_vendidos_t4 = tabla_productos_ordenada_tienda_4.head(10)

#gráfico de los 10 productos más y menos vendidos en la tienda 1
plt.barh(productos_mas_vendidos_t1["Producto"], productos_mas_vendidos_t1["Tienda 1"], color = "orange")
plt.title("Los productos más vendidos de la Tienda 1")
plt.xlabel("Cantidad de productos")
plt.show()

plt.barh(productos_menos_vendidos_t1["Producto"], productos_menos_vendidos_t1["Tienda 1"], color = "purple")
plt.title("Los productos menos vendidos de la Tienda 1")
plt.xlabel("Cantidad de productos")
plt.show()

#Gráfico de los 10 productos más y menos vendidos en la tienda 2
plt.barh(productos_mas_vendidos_t2["Producto"], productos_mas_vendidos_t2["Tienda 2"], color = "yellow")
plt.title("Los productos más vendidos de la Tienda 2")
plt.xlabel("Cantidad de productos")
plt.show()

plt.barh(productos_menos_vendidos_t2["Producto"], productos_menos_vendidos_t2["Tienda 2"], color = "silver")
plt.title("Los productos menos vendidos de la Tienda 2")
plt.xlabel("Cantidad de productos")
plt.show()

#Gráfico de los 10 productos más y menos vendidos en la tienda 3
plt.barh(productos_mas_vendidos_t3["Producto"], productos_mas_vendidos_t3["Tienda 3"], color = "navy")
plt.title("Los productos más vendidos de la Tienda 3")
plt.xlabel("Cantidad de productos")
plt.show()

plt.barh(productos_menos_vendidos_t3["Producto"], productos_menos_vendidos_t3["Tienda 3"], color = "red")
plt.title("Los productos menos vendidos de la Tienda 3")
plt.xlabel("Cantidad de productos")
plt.show()

#Gráfico de los 10 productos más y menos vendidos en la tienda 4
plt.barh(productos_mas_vendidos_t4["Producto"], productos_mas_vendidos_t4["Tienda 4"], color = "purple")
plt.title("Los productos más vendidos de la Tienda 4")
plt.xlabel("Cantidad de productos")
plt.show()

plt.barh(productos_menos_vendidos_t4["Producto"], productos_menos_vendidos_t4["Tienda 4"], color = "pink")
plt.title("Los productos menos vendidos de la Tienda 4")
plt.xlabel("Cantidad de productos")
plt.show()

"""# 5. Envío promedio por tienda"""

#Calcula el envío promedio para cada tienda
envio_promedio_por_tienda = []
for i, una_tienda in enumerate(lista_tiendas):
  promedio_envios = sum(una_tienda["Costo de envío"]) / len(una_tienda['Costo de envío'])
  print(f"Costo del envío promedio de la Tienda {i + 1}: {promedio_envios:.2f}", "\n")
  envio_promedio_por_tienda.append(promedio_envios)

"""###5.1. Grafico del envío promedio por tienda 📊 🏪"""

#Gráfico de barras
plt.bar(tiendas, envio_promedio_por_tienda, color = "lightgreen")
plt.title("Costo del envío promedio para cada tienda")
plt.xlabel("Tiendas")
plt.ylabel("Monto")
plt.gcf().axes[0].yaxis.get_major_formatter().set_scientific(False)
plt.show()

"""#EXTRA: análisis del desempeño geográfico 🌎 📈"""

# crear una lista con las ciudades donde se realizan las ventas
lugares_de_ventas = tienda1['Lugar de Compra'].unique()

dic_temp = {}   #diccionario temporal con las ciudades
dic_temp["Ciudad de venta"] = lugares_de_ventas

# crear una lista de las cantidades de productos vendidos por tipo en cada tienda
ventas_por_ciudad = []
lista_auxiliar = []

for una_tienda in lista_tiendas:
  for ciudades in lugares_de_ventas:
    lista_auxiliar.append(list(una_tienda["Lugar de Compra"]).count(ciudades))
  ventas_por_ciudad.append(lista_auxiliar)
  lista_auxiliar = []

#crear un diccionario con 4 listas, una por tienda, con los lugares de las ventas
tabla_lugares_ventas = {llaves:valores for (llaves, valores) in zip(tiendas, ventas_por_ciudad)}

#agregar la columna del nombre de las ciudades al diccionario
tabla_lugares_ventas = {**dic_temp, **tabla_lugares_ventas}

#crear un DataFrame a partir del diccionario de la ubicación de las ventas (compras)
tabla_lugares = pd.DataFrame(tabla_lugares_ventas)

#muestrar la tabla
tabla_lugares.sort_values(by= "Tienda 1", ascending= False)